# Sets user-defined palette
palette = "catppuccin_mocha"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[Û∞ú¥](blue)"
error_symbol = "[Û±è≥](red)"
vimcmd_symbol = "[‚ùÆ](green)"

[directory]
truncation_length = 3
home_symbol = "~"
truncation_symbol = ".../"
style = "bold blue"
# fish_style_pwd_dir_length = 1

[username]
show_always = true
format = 'Û±ç¢ PixelDino - [„ÉÄ„É≥„Çø](maroon) in |[ Û∞ù∞ ](lavender)'

# palette tables should be last in the config ‚öìÔ∏è
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[cmd_duration]
format = 'took [Û±é´ $duration]($style)'

[git_branch]
symbol = 'Ôêò '
style = "fg:bright-blue bg:black"
format = '[ÓÇ∂](fg:surface0)[$symbol$branch(:$remote_branch)](fg:teal bg:surface0)[ÓÇ¥](surface0) '


[aws]
format = ' [$symbol($profile)(\($region\))(\[$duration\])]($style)'

[bun]
format = '[$symbol($version )]($style)'
symbol = 'Óó∫ '

[c]
format = ' [$symbol($version(-$name) )]($style)'

[cmake]
format = ' [$symbol($version )]($style)'

[cobol]
format = ' [$symbol($version )]($style)'

[conda]
format = ' [$symbol$environment ]($style)'

[crystal]
format = ' [$symbol($version )]($style)'

[daml]
format = ' [$symbol($version )]($style)'

[dart]
format = ' [$symbol($version )]($style)'

[deno]
format = ' [$symbol($version )]($style)'

[docker_context]
format = ' [$symbol$context ]($style)'

[dotnet]
format = ' [$symbol($version)(üéØ $tfm )]($style)'

[elixir]
format = ' [$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
format = ' [$symbol($version )]($style)'

[erlang]
format = ' [$symbol($version )]($style)'

[fennel]
format = ' [$symbol($version )]($style)'

[fossil_branch]
format = ' [$symbol$branch ]($style)'

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\) )]($style)'

[golang]
format = ' [$symbol($version )]($style)'

[gradle]
format = ' [$symbol($version )]($style)'

[guix_shell]
format = ' [$symbol ]($style)'

[git_status]
format = '[ÓÇ∂](fg:surface0)[$all_status$ahead_behind]($style bg:surface0)[ÓÇ¥](surface0)  '

[haskell]
format = ' [$symbol($version )]($style)'

[haxe]
format = ' [$symbol($version )]($style)'

[helm]
format = ' [$symbol($version )]($style)'

[hg_branch]
format = ' [$symbol$branch ]($style)'

[java]
format = ' [$symbol($version )]($style)'

[julia]
format = ' [$symbol($version )]($style)'

[kotlin]
format = ' [$symbol($version )]($style)'

[kubernetes]
format = ' [$symbol$context( \($namespace\) )]($style)'

[lua]
format = ' [$symbol($version )]($style)'

[memory_usage]
format = ' $symbol[$ram( | $swap )]($style)'

[meson]
format = ' [$symbol$project ]($style)'

[nim]
format = ' [$symbol($version )]($style)'

[nix_shell]
format = ' [$symbol$state( \($name\) )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[ocaml]
format = ' [$symbol($version)(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = ' [$symbol($version )]($style)'

[openstack]
format = ' [$symbol$cloud(\($project\) )]($style)'

[os]
format = ' [$symbol ]($style)'

[package]
format = ' [$symbol$version ]($style)'

[perl]
format = ' [$symbol($version )]($style)'

[php]
format = ' [$symbol($version )]($style)'

[pijul_channel]
format = ' [$symbol$channel ]($style)'

[pulumi]
format = ' [$symbol$stack ]($style)'

[purescript]
format = ' [$symbol($version )]($style)'

[python]
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'

[raku]
format = ' [$symbol($version-$vm_version )]($style)'

[red]
format = ' [$symbol($version )]($style)'

[ruby]
format = ' [$symbol($version )]($style)'

[rust]
format = ' [$symbol($version )]($style)'

[scala]
format = ' [$symbol($version )]($style)'

[spack]
format = ' [$symbol$environment ]($style)'

[sudo]
format = ' [as $symbol ]($style)'

[swift]
format = ' [$symbol($version )]($style)'

[terraform]
format = ' [$symbol$workspace ]($style)'

[time]
format = ' [$time ]($style)'

[vagrant]
format = ' [$symbol($version )]($style)'

[vlang]
format = ' [$symbol($version )]($style)'

[zig]
format = ' [$symbol($version )]($style)'

[solidity]
format = ' [$symbol($version )]($style)'
